### ISSUE TITLE
Why is there a problem adding links without formatting?

### ISSUE THREAD

**Issue by oshliaer** [tanaikech/RichTextAssistant#1]
I'm trying to figure out if this problem is a bug?

I expect that once added all links will be formatted by default. But this doesn't happen. It seems to me that this is a Spreadsheets bug.

Anyway. If I add links manually the formatting is fine.

If I add via `RichTextAssistant.appendTexts()` then only the first link is formatted.

![2024-03-18_09-55-51](https://github.com/tanaikech/RichTextAssistant/assets/5027939/6dc7a755-b680-4480-a077-3f6ae97bf6ed)

The sample for copy https://docs.google.com/spreadsheets/d/1GatDOM4T9YB3gFwv3GkfqdrsNI2wA7qCQempygcYjPg/edit?usp=sharing

**Comment by tanaikech** [comment]
Thank you for your comment. And, I apologize for my late response. Now, I noticed your report.

I understood your comment. So, I updated this library to v1.0.1. Please test it again. In the current stage, when RichTextValueBuilder is used, it seems that when `setTextStyle` is used after `setLinkUrl`, the style of the hyperlink is removed while the link is kept. So, it is required to set `setLinkUrl` after `setTextStyle`. I think that this might be an important point for managing RichText with Google Apps Script.

**Comment by oshliaer** [comment]
I confirm that the problem has gone away.

Thanks a lot

**Comment by tanaikech** [comment]
Thank you, too.

By the way, I thought that this might be useful for other users. So, I also posted it to my X.
https://twitter.com/tanaikech/status/1782236872938545523
